### ISSUE TITLE
运行socks_tunnel出错

### ISSUE THREAD

**Issue by luckypoem** [cctiger36/socks_tunnel#1]
hi。

root@ary:~# gem install socks_tunnel
root@ary:~# socks_tunnel
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/local/rvm/gems/ruby-2.3.0/gems/socks_tunnel-0.2.0/bin/socks_tunnel:3:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.3.0/bin/socks_tunnel:23:in`load'
    from /usr/local/rvm/gems/ruby-2.3.0/bin/socks_tunnel:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`eval'
    from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
root@ary:~#

怎么解决？thank you.

**Comment by cctiger36** [comment]
没有装 bundler 的关系
我把 bundler 加到依赖里了，升级一下应该就可以了
gem update socks_tunnel

或者直接装一下 bundler
gem install bundler

**Comment by luckypoem** [comment]
果然ok.非常感谢！
